# Generated by Django 6.0.5 on 2026-05-22 21:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownerName', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('UAH', 'UAH'), ('EUR', 'EUR')], max_length=3)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
