# Generated by Django 6.0.5 on 2026-05-24 10:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_account_user_alter_account_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('transaction_type', models.CharField(choices=[('WITHDRAW', 'WITHDRAW'), ('DEPOSIT', 'DEPOSIT')], default='DEPOSIT', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bank.account')),
            ],
        ),
    ]
