# Generated by Django 6.0.5 on 2026-05-24 21:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
