# Generated by Django 6.0.5 on 2026-05-25 16:44

import bank.functions
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_transfer_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(default=bank.functions.generate_card_number, max_length=16, unique=True)),
                ('cvv', models.CharField(default=bank.functions.generate_cvv, max_length=3)),
                ('expiry_date', models.DateField(default=bank.functions.default_expiry_date)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='bank.account')),
            ],
        ),
    ]
